# Generated by Django 4.2.17 on 2024-12-15 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 9, 27, 54, 899248, tzinfo=datetime.timezone.utc)),
        ),
    ]
