# Generated by Django 4.2.17 on 2025-01-02 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_rezume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
